name: PublicRepo
main: wang.allenyou.publicrepo.PublicRepoPlugin
version: 1.0-SNAPSHOT
api-version: 1.19
author: Allenyou
commands:
  openrepo:
    aliases:
      - "repopen"
      - "orepo"
      - "oro"
    usage: "/openrepo"
    description: "Open the public repository."
  opentrashcan:
    aliases:
      - "opentrash"
      - "ot"
    usage: "/opentrash"
    description: "Open a trash can."
